export const TOKENS = [
  { name: "--bg-canvas", value: "#f7f7f8" },
  { name: "--bg-panel", value: "#ffffff" },
  { name: "--bg-input", value: "#f5f5f7" },
  { name: "--bg-toolbar", value: "#ffffff" },
  { name: "--border", value: "#e5e5ea" },
  { name: "--text-primary", value: "#1a1a1a" },
  { name: "--text-muted", value: "#8e8e93" },
  { name: "--accent", value: "#2563eb" },
  { name: "--accent-hover", value: "#1d4ed8" },
  { name: "--focus-ring", value: "rgba(37, 99, 235, 0.4)" },
  { name: "--selection-outline", value: "#2563eb" },
  { name: "--selection-hover", value: "#c7c7cc" },
  { name: "--toast-bg", value: "#1a1a1a" },
  { name: "--toast-text", value: "#ffffff" },
  { name: "--scrollbar-tool-thumb", value: "rgba(142, 142, 147, 0.45)" },
  { name: "--scrollbar-tool-thumb-hover", value: "rgba(142, 142, 147, 0.7)" },
  { name: "--scroll-zone-active-ring", value: "rgba(37, 99, 235, 0.22)" },
];
