export const demoPageConfig = {
  elements: [
    {
      id: "heading-1",
      type: "heading",
      text: "Welcome to the demo page",
      color: "#1a1a1a",
      fontSize: 40,
      backgroundColor: "transparent",
      opacity: 100,
      padding: 0,
      marginBottom: 20,
      borderRadius: 0,
      borderWidth: 0,
      borderColor: "#000000",
      textAlign: "left",
      offsetX: 0,
      offsetY: 0,
      width: null,
      height: null,
    },
    {
      id: "paragraph-1",
      type: "paragraph",
      text: "Click Edit, select this text, and change it. Save, then refresh.",
      color: "#444444",
      fontSize: 18,
      backgroundColor: "transparent",
      opacity: 100,
      padding: 0,
      marginBottom: 20,
      borderRadius: 0,
      borderWidth: 0,
      borderColor: "#000000",
      textAlign: "left",
      offsetX: 0,
      offsetY: 0,
      width: null,
      height: null,
    },
  ],
};
