const cardDefaults = {
  type: "container",
  backgroundColor: "#ffffff",
  borderWidth: 1,
  borderColor: "#e5e5ea",
  borderRadius: 12,
  padding: 20,
  width: 300,
  height: 220,
  opacity: 100,
  marginBottom: 0,
};

function toolCard(id, title, description, label, offsetX) {
  return {
    ...cardDefaults,
    id,
    offsetX,
    offsetY: 268,
    children: [
      {
        id: `${id}-title`,
        type: "heading",
        text: title,
        fontSize: 20,
        color: "#111827",
        marginBottom: 8,
        offsetX: 0,
        offsetY: 0,
        width: null,
        height: null,
        backgroundColor: "transparent",
        opacity: 100,
        padding: 0,
        borderRadius: 0,
        borderWidth: 0,
        borderColor: "#000000",
        textAlign: "left",
      },
      {
        id: `${id}-desc`,
        type: "paragraph",
        text: description,
        fontSize: 14,
        color: "#6b7280",
        marginBottom: 16,
        offsetX: 0,
        offsetY: 0,
        width: null,
        height: null,
        backgroundColor: "transparent",
        opacity: 100,
        padding: 0,
        borderRadius: 0,
        borderWidth: 0,
        borderColor: "#000000",
        textAlign: "left",
      },
      {
        id: `${id}-btn`,
        type: "button",
        label,
        href: "",
        target: "_self",
        fontSize: 14,
        color: "#ffffff",
        backgroundColor: "#111827",
        padding: 10,
        borderRadius: 8,
        marginBottom: 0,
        offsetX: 0,
        offsetY: 0,
        width: null,
        height: null,
        opacity: 100,
        borderWidth: 0,
        borderColor: "#000000",
        textAlign: "left",
      },
    ],
  };
}

export const mcpMarketplaceConfig = {
  elements: [
    {
      id: "mp-badge",
      type: "paragraph",
      text: "CURSOR MCP TOOLS",
      color: "#6366f1",
      fontSize: 12,
      backgroundColor: "transparent",
      opacity: 100,
      padding: 0,
      marginBottom: 12,
      borderRadius: 0,
      borderWidth: 0,
      borderColor: "#000000",
      textAlign: "left",
      offsetX: 0,
      offsetY: 0,
      width: null,
      height: null,
    },
    {
      id: "mp-title",
      type: "heading",
      text: "MCP Marketplace",
      color: "#111827",
      fontSize: 48,
      backgroundColor: "transparent",
      opacity: 100,
      padding: 0,
      marginBottom: 12,
      borderRadius: 0,
      borderWidth: 0,
      borderColor: "#000000",
      textAlign: "left",
      offsetX: 0,
      offsetY: 0,
      width: null,
      height: null,
    },
    {
      id: "mp-subtitle",
      type: "paragraph",
      text: "Discover Model Context Protocol servers you can plug into Cursor. Browse tools, compare capabilities, and install what you need.",
      color: "#374151",
      fontSize: 18,
      backgroundColor: "transparent",
      opacity: 100,
      padding: 0,
      marginBottom: 24,
      borderRadius: 0,
      borderWidth: 0,
      borderColor: "#000000",
      textAlign: "left",
      offsetX: 0,
      offsetY: 0,
      width: 680,
      height: null,
    },
    {
      id: "mp-divider",
      type: "divider",
      dividerThickness: 1,
      dividerColor: "#e5e7eb",
      width: 960,
      height: null,
      marginBottom: 32,
      offsetX: 0,
      offsetY: 0,
      backgroundColor: "transparent",
      opacity: 100,
      padding: 0,
      borderRadius: 0,
      borderWidth: 0,
      borderColor: "#000000",
      textAlign: "left",
      color: "#1a1a1a",
      fontSize: 16,
    },
    {
      id: "mp-section-label",
      type: "heading",
      text: "Featured tools",
      color: "#111827",
      fontSize: 22,
      backgroundColor: "transparent",
      opacity: 100,
      padding: 0,
      marginBottom: 20,
      borderRadius: 0,
      borderWidth: 0,
      borderColor: "#000000",
      textAlign: "left",
      offsetX: 0,
      offsetY: 0,
      width: null,
      height: null,
    },
    toolCard(
      "mp-card-github",
      "GitHub MCP",
      "Search repos, read issues, and open pull requests without leaving the editor.",
      "Install",
      0
    ),
    toolCard(
      "mp-card-slack",
      "Slack MCP",
      "Send messages, search channels, and triage notifications from your workspace.",
      "Install",
      330
    ),
    toolCard(
      "mp-card-linear",
      "Linear MCP",
      "Create issues, update status, and sync sprint work with your codebase.",
      "Install",
      660
    ),
    {
      id: "mp-footer",
      type: "paragraph",
      text: "Tip: switch to Edit mode and rearrange cards, tweak copy, or insert new tool rows.",
      color: "#9ca3af",
      fontSize: 14,
      backgroundColor: "transparent",
      opacity: 100,
      padding: 0,
      marginBottom: 0,
      borderRadius: 0,
      borderWidth: 0,
      borderColor: "#000000",
      textAlign: "left",
      offsetX: 0,
      offsetY: 520,
      width: 640,
      height: null,
    },
  ],
};
